export const GROUND_HEIGHT = 120;
export const SODA_BOX_HEIGHT = 90;
export const SODA_BOX_WIDTH = (SODA_BOX_HEIGHT * 3) / 4;
export const TIME_DELAY = 600;
export const SODA_Y_POSITION = 110;
export const HAND_Y_POSITION = 25;
export const SVG_SCALING = 0.825;
export const SPEED = 1.4;
export const MAX_SPEED = 6;
